In [1]:
import numpy as np
import pandas as pd

In [2]:
retail_df = pd.read_csv('./assets/retail.csv')

In [39]:
condition = (retail_df['family'].isin(['BEVERAGES', 'DIARY', 'DELI'])) & (retail_df['sales'] > 0)
sample_df = retail_df.loc[condition].sample(5, random_state=112)
sample_df

             id        date  store_nbr     family     sales  onpromotion
566553  2512497  2016-11-13          6       DELI   613.950           15
276477  2222421  2016-06-04         17  BEVERAGES  4164.000            4
311100  2257044  2016-06-23         38       DELI   116.445            3
836256  2782200  2017-04-15         23  BEVERAGES  1726.000           24
891036  2836980  2017-05-16         10  BEVERAGES  1237.000           19

In [44]:
sample_df.astype({'family': 'category'}).info()

<class 'pandas.DataFrame'>
Index: 5 entries, 566553 to 891036
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5 non-null      int64
 1   date         5 non-null      str
 2   store_nbr    5 non-null      int64
 3   family       5 non-null      category
 4   sales        5 non-null      float64
 5   onpromotion  5 non-null      int64
dtypes: category(1), float64(1), int64(3), str(1)
memory usage: 326.0 bytes

In [48]:
retail_df.info(memory_usage='deep')
retail_df.astype({'family': 'category'}).info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  str
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  str
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), str(2)
memory usage: 69.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  str
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  category
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: category(1), float64(1), int64(3), str(1)
memory usage: 51.3 MB

In [50]:
sample_df.assign(
    sales_int = sample_df.sales.astype('int')
)

,id,date,store_nbr,family,sales,onpromotion,sales_int
566553,2512497,2016-11-13,6,DELI,613.950,15,613
276477,2222421,2016-06-04,17,BEVERAGES,4164.000,4,4164
311100,2257044,2016-06-23,38,DELI,116.445,3,116
836256,2782200,2017-04-15,23,BEVERAGES,1726.000,24,1726
891036,2836980,2017-05-16,10,BEVERAGES,1237.000,19,1237

In [53]:
sample_df.astype({'date': 'datetime64[ns]', 'onpromotion': 'float'}).info()

<class 'pandas.DataFrame'>
Index: 5 entries, 566553 to 891036
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5 non-null      int64
 1   date         5 non-null      datetime64[ns]
 2   store_nbr    5 non-null      int64
 3   family       5 non-null      str
 4   sales        5 non-null      float64
 5   onpromotion  5 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(2), str(1)
memory usage: 316.0 bytes

In [58]:
retail_df.memory_usage(deep=True)

Index               132
id              8439552
date           18988992
store_nbr       8439552
family         19788192
sales           8439552
onpromotion     8439552
dtype: int64