In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.DataFrame(
    {'id': [1, 2],
     'store_nbr': [1, 2],
     'family': ['POULTRY', 'PRODUCE']
    }
)

   id  store_nbr   family
0   1          1  POULTRY
1   2          2  PRODUCE

In [5]:
retail_df = pd.read_csv('./assets/retail.csv')
retail_df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [7]:
oil = pd.read_csv('./assets/oil.csv')
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [8]:
oil.shape

(1218, 2)

In [9]:
oil.axes

[RangeIndex(start=0, stop=1218, step=1),
 Index(['date', 'dcoilwtico'], dtype='str')]

In [10]:
oil.index

RangeIndex(start=0, stop=1218, step=1)

In [11]:
oil.columns

Index(['date', 'dcoilwtico'], dtype='str')

In [12]:
oil.size

2436

In [16]:
oil.columns = ['price_date', 'oil_price']
oil.columns

Index(['price_date', 'oil_price'], dtype='str')

In [17]:
oil.dtypes

price_date        str
oil_price     float64
dtype: object