In [8]:
import numpy as np
import pandas as pd

In [9]:
pd.set_option("display.float_format", '{:,.2f}'.format)

In [10]:
retail = pd.read_csv('./assets/retail.csv')

In [11]:
(retail.assign(store_sales = retail.groupby('store_nbr')['sales']
               .transform("sum"))
)

,id,date,store_nbr,family,sales,onpromotion,store_sales
0,1945944,2016-01-01,1,AUTOMOTIVE,0.00,0,"6,230,010.98"
1,1945945,2016-01-01,1,BABY CARE,0.00,0,"6,230,010.98"
2,1945946,2016-01-01,1,BEAUTY,0.00,0,"6,230,010.98"
3,1945947,2016-01-01,1,BEVERAGES,0.00,0,"6,230,010.98"
4,1945948,2016-01-01,1,BOOKS,0.00,0,"6,230,010.98"
...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.13,0,"11,172,895.26"
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.55,1,"11,172,895.26"
1054941,3000885,2017-08-15,9,PRODUCE,"2,419.73",148,"11,172,895.26"
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.00,8,"11,172,895.26"
1054943,3000887,2017-08-15,9,SEAFOOD,16.00,0,"11,172,895.26"

In [13]:
premier_league = pd.read_csv('./assets/premier_league_games.csv')
premier_league.head()

,id,league_name,season,home_team,away_team,home_goals,away_goals
0,1,Premier League,1993/1994,Arsenal,Coventry,0,3
1,2,Premier League,1993/1994,Aston Villa,QPR,4,1
2,3,Premier League,1993/1994,Chelsea,Blackburn,1,2
3,4,Premier League,1993/1994,Liverpool,Sheffield Weds,2,0
4,5,Premier League,1993/1994,Man City,Leeds,1,1

In [26]:
pm = premier_league.assign(
    avg_home_team_home_goals = premier_league.groupby('home_team')['home_goals']
        .transform('mean'),
    difference = lambda x : x['home_goals'] - x['avg_home_team_home_goals']
)

pm.loc[pm['difference'] > 0]

,id,league_name,season,home_team,away_team,home_goals,away_goals,avg_home_team_home_goals,difference
1,2,Premier League,1993/1994,Aston Villa,QPR,4,1,1.39,2.61
7,8,Premier League,1993/1994,Sheffield United,Swindon,3,1,1.06,1.94
16,17,Premier League,1993/1994,Blackburn,Norwich,2,3,1.55,0.45
17,18,Premier League,1993/1994,Coventry,Newcastle,2,1,1.22,0.78
18,19,Premier League,1993/1994,Man United,Sheffield United,3,0,2.07,0.93
...,...,...,...,...,...,...,...,...,...
12690,12691,Premier League,2025/2026,Newcastle,West Ham,3,1,1.67,1.33
12693,12694,Premier League,2025/2026,Chelsea,Tottenham,2,1,1.93,0.07
12697,12698,Premier League,2025/2026,Fulham,Newcastle,2,0,1.38,0.62
12701,12702,Premier League,2025/2026,Sunderland,Chelsea,2,1,1.12,0.88
12703,12704,Premier League,2025/2026,West Ham,Leeds,3,0,1.46,1.54

In [31]:
pm.groupby(['home_team', 'away_team']).agg({'difference': 'mean'}).loc['Arsenal'].sort_values('difference', ascending=False)

                  difference
away_team
Blackpool               3.93
Barnsley                2.93
Huddersfield            0.93
Sheffield United        0.73
Norwich                 0.71
Charlton                0.68
Leeds                   0.60
Reading                 0.60
Wigan                   0.56
Leicester               0.54
Portsmouth              0.50
Stoke                   0.43
Bournemouth             0.37
Ipswich                 0.33
Nott'm Forest           0.31
Everton                 0.29
Middlesbrough           0.29
Blackburn               0.28
Southampton             0.26
West Brom               0.24
Bolton                  0.24
Sheffield Weds          0.22
Fulham                  0.19
Watford                 0.18
Crystal Palace          0.18
Burnley                 0.13
Newcastle               0.09
Tottenham               0.05
Sunderland              0.05
Aston Villa            -0.04
Luton                  -0.07
Hull                   -0.07
Bradford               -0.07
Cardiff                -0.07
Wolves                 -0.15
West Ham               -0.20
Wimbledon              -0.21
Birmingham             -0.36
Derby                  -0.36
Man United             -0.43
Brentford              -0.47
Chelsea                -0.49
Coventry               -0.57
Man City               -0.64
Liverpool              -0.65
Brighton               -0.74
QPR                    -0.74
Swansea                -0.78
Oldham                 -1.07
Swindon                -1.07

In [34]:
pm.query("home_team == 'Arsenal' and away_team == 'Blackpool'")

,id,league_name,season,home_team,away_team,home_goals,away_goals,avg_home_team_home_goals,difference
6634,6635,Premier League,2010/2011,Arsenal,Blackpool,6,0,2.07,3.93

In [36]:
pm.query("away_team == 'Blackpool'")

,id,league_name,season,home_team,away_team,home_goals,away_goals,avg_home_team_home_goals,difference
6630,6631,Premier League,2010/2011,Wigan,Blackpool,0,4,1.11,-1.11
6634,6635,Premier League,2010/2011,Arsenal,Blackpool,6,0,2.07,3.93
6658,6659,Premier League,2010/2011,Newcastle,Blackpool,0,2,1.67,-1.67
6671,6672,Premier League,2010/2011,Chelsea,Blackpool,4,0,1.93,2.07
6692,6693,Premier League,2010/2011,Liverpool,Blackpool,1,2,2.04,-1.04
6704,6705,Premier League,2010/2011,Birmingham,Blackpool,2,0,1.22,0.78
6736,6737,Premier League,2010/2011,Aston Villa,Blackpool,3,2,1.39,1.61
6749,6750,Premier League,2010/2011,West Ham,Blackpool,0,0,1.46,-1.46
6765,6766,Premier League,2010/2011,Bolton,Blackpool,2,2,1.29,0.71
6787,6788,Premier League,2010/2011,Stoke,Blackpool,0,1,1.31,-1.31
6807,6808,Premier League,2010/2011,Sunderland,Blackpool,0,2,1.12,-1.12
6816,6817,Premier League,2010/2011,Man City,Blackpool,1,0,2.10,-1.10
6838,6839,Premier League,2010/2011,West Brom,Blackpool,3,2,1.19,1.81
6869,6870,Premier League,2010/2011,Everton,Blackpool,5,3,1.50,3.50
6896,6897,Premier League,2010/2011,Wolves,Blackpool,4,0,1.19,2.81
6913,6914,Premier League,2010/2011,Blackburn,Blackpool,2,2,1.55,0.45
6930,6931,Premier League,2010/2011,Fulham,Blackpool,3,0,1.38,1.62
6977,6978,Premier League,2010/2011,Tottenham,Blackpool,1,1,1.72,-0.72
6998,6999,Premier League,2010/2011,Man United,Blackpool,4,2,2.07,1.93