In [1]:
import numpy as np
import pandas as pd

In [3]:
retail = pd.read_csv("./assets/retail.csv")
retail.groupby('family')

In [9]:
retail.groupby('family')[['sales']].sum().head()

                  sales
family
AUTOMOTIVE     226139.0
BABY CARE        7903.0
BEAUTY         166189.0
BEVERAGES   105700279.0
BOOKS            6438.0

In [10]:
premier_league = pd.read_csv('./assets/premier_league_games.csv')
premier_league.head()

,id,league_name,season,home_team,away_team,home_goals,away_goals
0,1,Premier League,1993/1994,Arsenal,Coventry,0,3
1,2,Premier League,1993/1994,Aston Villa,QPR,4,1
2,3,Premier League,1993/1994,Chelsea,Blackburn,1,2
3,4,Premier League,1993/1994,Liverpool,Sheffield Weds,2,0
4,5,Premier League,1993/1994,Man City,Leeds,1,1

In [15]:
premier_league.groupby('home_team')[['home_goals']].mean().sort_values('home_goals', ascending=False).head()

            home_goals
home_team
Man City      2.100746
Arsenal       2.069731
Man United    2.066561
Liverpool     2.038035
Chelsea       1.928685

In [16]:
premier_league.groupby('away_team')[['away_goals']].mean().sort_values('away_goals', ascending=False).head()

            away_goals
away_team
Man United    1.651347
Arsenal       1.568938
Liverpool     1.557845
Man City      1.520522
Chelsea       1.492868