In [1]:
import numpy as np
import pandas as pd

In [3]:
retail = pd.read_csv("./assets/retail.csv")
retail.groupby('family')

In [9]:
retail.groupby('family')[['sales']].sum().head()

                  sales
family
AUTOMOTIVE     226139.0
BABY CARE        7903.0
BEAUTY         166189.0
BEVERAGES   105700279.0
BOOKS            6438.0

In [10]:
premier_league = pd.read_csv('./assets/premier_league_games.csv')
premier_league.head()

,id,league_name,season,home_team,away_team,home_goals,away_goals
0,1,Premier League,1993/1994,Arsenal,Coventry,0,3
1,2,Premier League,1993/1994,Aston Villa,QPR,4,1
2,3,Premier League,1993/1994,Chelsea,Blackburn,1,2
3,4,Premier League,1993/1994,Liverpool,Sheffield Weds,2,0
4,5,Premier League,1993/1994,Man City,Leeds,1,1

In [15]:
premier_league.groupby('home_team')[['home_goals']].mean().sort_values('home_goals', ascending=False).head()

            home_goals
home_team
Man City      2.100746
Arsenal       2.069731
Man United    2.066561
Liverpool     2.038035
Chelsea       1.928685

In [16]:
premier_league.groupby('away_team')[['away_goals']].mean().sort_values('away_goals', ascending=False).head()

            away_goals
away_team
Man United    1.651347
Arsenal       1.568938
Liverpool     1.557845
Man City      1.520522
Chelsea       1.492868

In [17]:
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [20]:
# multi index
retail.groupby(['family', 'store_nbr'])[['sales']].sum()

                             sales
family     store_nbr
AUTOMOTIVE 1           2524.000000
           2           3918.000000
           3           6790.000000
           4           2565.000000
           5           3667.000000
...                            ...
SEAFOOD    50         12773.966999
           51         34250.948976
           52          1219.475999
           53          3745.180001
           54          1082.000000

[1782 rows x 1 columns]

In [22]:
retail.groupby(['family', 'store_nbr'], as_index=False)[['sales']].sum()

          family  store_nbr         sales
0     AUTOMOTIVE          1   2524.000000
1     AUTOMOTIVE          2   3918.000000
2     AUTOMOTIVE          3   6790.000000
3     AUTOMOTIVE          4   2565.000000
4     AUTOMOTIVE          5   3667.000000
...          ...        ...           ...
1777     SEAFOOD         50  12773.966999
1778     SEAFOOD         51  34250.948976
1779     SEAFOOD         52   1219.475999
1780     SEAFOOD         53   3745.180001
1781     SEAFOOD         54   1082.000000

[1782 rows x 3 columns]

In [32]:
(premier_league.groupby(['home_team', 'season'], as_index=False)[['home_goals']].sum()
    .sort_values(['home_team', 'season'], ascending=[True, False]))

    home_team     season  home_goals
32    Arsenal  2025/2026          41
31    Arsenal  2024/2025          35
30    Arsenal  2023/2024          48
29    Arsenal  2022/2023          53
28    Arsenal  2021/2022          35
..        ...        ...         ...
656    Wolves  2018/2019          28
655    Wolves  2011/2012          19
654    Wolves  2010/2011          30
653    Wolves  2009/2010          13
652    Wolves  2003/2004          23

[664 rows x 3 columns]